<a href="https://colab.research.google.com/github/alexanderbasalgin/python_polytech/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа по теме: "Введение в анализ данных. Операции над векторами и матрицами в NumPy"

In [3]:
import numpy as np

### Задание 1

Создать 12x12 единичную матрицу (с единицами по диагонали)

In [6]:
matrix = np.eye(12)
print(matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### Задание 2 *

Создать 9x9 матрицу и заполнить её в шахматном порядке

In [9]:
matrix = np.zeros((9, 9), dtype=int)
for i in range(9):
    for j in range(9):
        if (i + j) % 2 == 0:
            matrix[i, j] = 1
print(matrix)

[[1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 1]]


### Задание 3

Отсортировать произвольный вектор в порядке возрастания

In [14]:
np.random.seed(42)
vector = np.random.random(10)
print(vector)
vector = np.sort(vector)
print(vector)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
[0.05808361 0.15599452 0.15601864 0.37454012 0.59865848 0.60111501
 0.70807258 0.73199394 0.86617615 0.95071431]


### Задание 4

Определить есть ли в произвольном двумерном массиве из целых чисел строки, в которых все значения равны 4.

In [38]:
np.random.seed(42)
fourth_array = np.random.randint(3, 5,(8, 3))
print(fourth_array)
check_4 = np.all(fourth_array == 4, axis=1)
if np.any(check_4):
    print('В произвольном двумерном массиве есть строки, в которых все значения равны 4')
else:
    print('В произвольном двумерном массиве нет строк, в которых все значения равны 4')


[[3 4 3]
 [3 3 4]
 [3 3 3]
 [4 3 3]
 [3 3 4]
 [3 4 4]
 [4 3 4]
 [3 4 4]]
В произвольном двумерном массиве нет строк, в которых все значения равны 4


### Задание 5

Создайте массив из 6 элементов, 5 из которых равны 0, последний элемент должен быть равен 1

In [34]:
array = np.zeros(6)
array[-1] = 1
print(array)

[0. 0. 0. 0. 0. 1.]


### Задание 6

Укажите индекс 9 элемента в массиве 2х3х2

In [39]:
index = np.unravel_index(9, (2, 3, 2))
print(index)

(1, 1, 1)
